// <auto-generated />
namespace IAmDbProject.DataContexts.IAmDbProjectDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Wed42016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wed42016));
        
        string IMigrationMetadata.Id
        {
            get { return "201604201620544_Wed42016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
